(()=>{"use strict";
const c=document.getElementById("gameCanvas"),x=c.getContext("2d"),$=id=>document.getElementById(id);
const L=$("level"),B=$("bottles"),A=$("bullets"),S=$("score"),BEST=$("best"),msg=$("message"),count=$("countdown"),cross=$("crosshair"),hint=$("hint");
let W,H,dpr=1,level=1,score=0,best=+localStorage.kakaBest||0,bullets=0,bottles=[],parts=[],tracers=[],running=false,paused=false,sound=true,ptr={x:0,y:0},shake=0,last=0;
const levels=[{n:5,b:7,v:0,s:1},{n:7,b:9,v:0,s:.94},{n:8,b:10,v:.45,s:.91},{n:10,b:12,v:.7,s:.87},{n:12,b:14,v:.95,s:.83},{n:14,b:16,v:1.15,s:.79},{n:16,b:18,v:1.35,s:.75}];
function resize(){let r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0);if(!ptr.x){ptr.x=W/2;ptr.y=H*.5}}addEventListener("resize",resize);resize();
function pad(n){return String(n).padStart(6,"0")}BEST.textContent=pad(best);
function hud(){L.textContent=level;B.textContent=bottles.filter(q=>q.alive).length+"/"+bottles.length;A.textContent=bullets;S.textContent=pad(score);BEST.textContent=pad(best)}
function setup(n){level=n;let q=levels[Math.min(n-1,levels.length-1)];bullets=q.b;bottles=[];let cols=Math.min(8,Math.ceil(Math.sqrt(q.n*1.55))),rows=Math.ceil(q.n/cols),gx=Math.min(105,W*.72/Math.max(cols-1,1)),gy=Math.min(105,H*.14),sx=W/2-(cols-1)*gx/2,sy=H*.32;for(let i=0;i<q.n;i++){let col=i%cols,row=Math.floor(i/cols);bottles.push({x:sx+col*gx,y:sy+row*gy,bx:sx+col*gx,by:sy+row*gy,v:q.v,ph:Math.random()*6.28,s:q.s,alive:true})}running=false;paused=false;hint.textContent="AIM • CLICK / TAP TO FIRE";hud();let n3=3;count.classList.remove("hidden");count.textContent=n3;let t=setInterval(()=>{n3--;if(n3>0)count.textContent=n3;else{clearInterval(t);count.textContent="GO!";setTimeout(()=>{count.classList.add("hidden");running=true},300)}},600)}
function audio(kind){if(!sound)return;try{window.ac||(window.ac=new(window.AudioContext||webkitAudioContext));let o=ac.createOscillator(),g=ac.createGain(),z=ac.currentTime;o.connect(g);g.connect(ac.destination);o.type=kind==="shot"?"square":"sine";o.frequency.setValueAtTime(kind==="shot"?120:720,z);o.frequency.exponentialRampToValueAtTime(kind==="shot"?55:300,z+.1);g.gain.setValueAtTime(.05,z);g.gain.exponentialRampToValueAtTime(.001,z+.11);o.start();o.stop(z+.12)}catch(e){}}
function burst(px,py,good){for(let i=0;i<(good?25:8);i++){let a=Math.random()*6.28,v=(good?2:1)+Math.random()*4;parts.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v-1,life:1,size:good?2+Math.random()*4:2})}}
function fire(){if(!running||paused||!bullets)return;bullets--;tracers.push({x:W/2,y:H,tx:ptr.x,ty:ptr.y,t:0});audio("shot");shake=7;let hit=null,dist=1e9;for(let q of bottles)if(q.alive){let d=Math.hypot(ptr.x-q.x,ptr.y-q.y);if(d<29*q.s&&d<dist){hit=q;dist=d}}if(hit){hit.alive=false;score+=100+bullets*8;burst(hit.x,hit.y,true);audio("hit")}else{score=Math.max(0,score-10);burst(ptr.x,ptr.y,false)}hud();let left=bottles.filter(q=>q.alive).length;if(!left){running=false;let bonus=bullets*35;score+=bonus;if(score>best){best=score;localStorage.kakaBest=best}hud();setTimeout(()=>panel("ROUND CLEAR","+"+bonus+" bonus points","NEXT ROUND →",()=>setup(level+1)),550)}else if(!bullets){running=false;setTimeout(()=>panel("GAME OVER","You cleared "+(bottles.length-left)+" of "+bottles.length+" bottles.","TRY AGAIN",()=>setup(1)),500)}}
function panel(title,sub,button,action){msg.innerHTML="<h2>"+title+"</h2><p>"+sub+"</p><button>"+button+"</button>";msg.classList.remove("hidden");msg.querySelector("button").onclick=()=>{msg.classList.add("hidden");action()}}
function bg(t){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,"#0b1a2d");g.addColorStop(.58,"#10243a");g.addColorStop(1,"#07111e");x.fillStyle=g;x.fillRect(0,0,W,H);let gl=x.createRadialGradient(W/2,H*.35,5,W/2,H*.35,W*.7);gl.addColorStop(0,"#48bee622");gl.addColorStop(1,"transparent");x.fillStyle=gl;x.fillRect(0,0,W,H);x.fillStyle="#1a3040";x.fillRect(0,H*.63,W,H*.37);x.fillStyle="#243f4d";x.fillRect(0,H*.61,W,10)}
function bottle(q,t){x.save();x.translate(q.x,q.y);x.scale(q.s,q.s);x.fillStyle="#0006";x.beginPath();x.ellipse(0,34,25,7,0,0,6.28);x.fill();let g=x.createLinearGradient(-20,0,20,0);g.addColorStop(0,"#6a160f");g.addColorStop(.3,"#e8492e");g.addColorStop(.65,"#ff7b3e");g.addColorStop(1,"#8c2118");x.fillStyle=g;x.beginPath();x.roundRect(-20,-4,40,38,7);x.fill();x.fillStyle="#f9c14b";x.fillRect(-20,8,40,7);x.fillStyle="#f3f5e8";x.fillRect(-12,-20,24,17);x.fillStyle="#b7d9df";x.fillRect(-10,-18,20,12);x.fillStyle="#b9d4d5";x.fillRect(-14,-25,28,6);x.fillStyle="#fff6";x.fillRect(-14,-1,4,28);x.restore()}
function pistol(){let ang=Math.atan2(ptr.y-(H+30),ptr.x-W/2);x.save();x.translate(W/2,H+35);x.rotate(ang+Math.PI/2);x.translate(0,shake);x.fillStyle="#111923";x.beginPath();x.roundRect(-14,-72,28,74,7);x.fill();x.fillStyle="#2d3a47";x.fillRect(-9,-82,18,30);x.fillStyle="#161d26";x.beginPath();x.roundRect(-13,0,26,55,5);x.fill();x.restore()}
function draw(t){x.clearRect(0,0,W,H);bg(t);for(let q of bottles)if(q.alive)bottle(q,t);for(let q of tracers){let e=Math.min(1,q.t),px=q.x+(q.tx-q.x)*e,py=q.y+(q.ty-q.y)*e;x.strokeStyle="#ffe585";x.lineWidth=2;x.beginPath();x.moveTo(q.x,q.y);x.lineTo(px,py);x.stroke()}for(let p of parts){x.globalAlpha=Math.max(0,p.life);x.fillStyle="#ffd34e";x.beginPath();x.arc(p.x,p.y,p.size,0,6.28);x.fill()}x.globalAlpha=1;pistol()}
function tick(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(!paused){for(let q of bottles)if(q.alive&&q.v)q.x=q.bx+Math.sin(t*.001*q.v+q.ph)*18*q.v;for(let p of parts){p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vy+=.08;p.life-=dt*1.8}parts=parts.filter(p=>p.life>0);for(let q of tracers)q.t+=dt*8;tracers=tracers.filter(q=>q.t<1);shake=Math.max(0,shake-dt*25)}draw(t);requestAnimationFrame(tick)}
function move(e){let r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;ptr.x=Math.max(0,Math.min(W,p.clientX-r.left));ptr.y=Math.max(0,Math.min(H,p.clientY-r.top));cross.style.left=ptr.x+"px";cross.style.top=ptr.y+"px"}
c.addEventListener("pointermove",move);c.addEventListener("pointerdown",e=>{move(e);fire()});c.addEventListener("touchstart",e=>{e.preventDefault();move(e);fire()},{passive:false});
$("pauseBtn").onclick=()=>{if(!running)return;paused=!paused;$("pauseBtn").textContent=paused?"▶":"Ⅱ";hint.textContent=paused?"PAUSED":"AIM • CLICK / TAP TO FIRE"};
$("soundBtn").onclick=()=>{sound=!sound;$("soundBtn").textContent=sound?"🔊":"🔇"};
$("restartBtn").onclick=()=>{msg.classList.add("hidden");setup(1)};setup(1);requestAnimationFrame(tick);
})();