(()=>{"use strict";
const c=document.getElementById("gameCanvas"),x=c.getContext("2d"),$=id=>document.getElementById(id);
const L=$("level"),B=$("bottles"),A=$("bullets"),S=$("score"),BEST=$("best"),msg=$("message"),count=$("countdown"),cross=$("crosshair"),hint=$("hint");
let W,H,dpr=1,level=1,score=0,best=+localStorage.digShooterBest||0,bullets=0,targets=[],parts=[],tracers=[],running=false,paused=false,sound=true,ptr={x:0,y:0},shake=0,last=0,combo=0,timeLeft=0,mode="",thrower={x:0,y:0,arm:0};
const scenarios=[
{name:"LIVE THROW",n:12,b:18,time:0,v:1,types:["bottle","plate","bird"]},
{name:"RAPID THROW",n:15,b:19,time:0,v:1.3,types:["bottle","plate","bird"]},
{name:"CROSSING SKY",n:18,b:21,time:42,v:1.55,types:["bird","plate","bottle"]},
{name:"CLAY & GLASS",n:20,b:23,time:40,v:1.8,types:["bottle","plate"]},
{name:"FULL RANGE",n:24,b:27,time:38,v:2,types:["bottle","bird","plate"]},
{name:"REACTION",n:26,b:28,time:35,v:2.25,types:["bird","plate","bottle"]},
{name:"FINAL RANGE",n:30,b:32,time:34,v:2.5,types:["bottle","bird","plate"]}];
function resize(){let r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0);if(!ptr.x){ptr.x=W/2;ptr.y=H*.5}}addEventListener("resize",resize);resize();
function pad(n){return String(Math.max(0,Math.floor(n))).padStart(6,"0")}BEST.textContent=pad(best);
function hud(){L.textContent=level;B.textContent=targets.filter(q=>q.alive).length+"/"+targets.length;A.textContent=bullets;S.textContent=pad(score);BEST.textContent=pad(best)}
function setup(n){level=n;let q=scenarios[Math.min(n-1,scenarios.length-1)];mode=q.name;bullets=q.b;timeLeft=q.time;combo=0;targets=[];running=false;paused=false;for(let i=0;i<q.n;i++){let type=q.types[i%q.types.length];targets.push({x:0,y:0,v:q.v*(.8+Math.random()*.35),s:type==="plate"?.72:type==="bird"?.68:.75,alive:true,type,phase:Math.random()*6.28,delay:i*.23,life:0,dir:i%2?1:-1,spin:Math.random()*6.28,red:i%7===0})}hud();hint.textContent="WATCH THE THROWER • TRACK THE AIRBORNE TARGET";let n3=3;count.classList.remove("hidden");count.textContent=n3;let timer=setInterval(()=>{n3--;if(n3>0)count.textContent=n3;else{clearInterval(timer);count.textContent="GO";setTimeout(()=>{count.classList.add("hidden");running=true},350)}},600)}
function audio(kind){if(!sound)return;try{window.ac||(window.ac=new(window.AudioContext||webkitAudioContext));let o=ac.createOscillator(),g=ac.createGain(),z=ac.currentTime;o.connect(g);g.connect(ac.destination);o.type=kind==="shot"?"square":"sine";o.frequency.setValueAtTime(kind==="shot"?110:kind==="hit"?680:190,z);o.frequency.exponentialRampToValueAtTime(kind==="shot"?48:kind==="hit"?280:90,z+.1);g.gain.setValueAtTime(.045,z);g.gain.exponentialRampToValueAtTime(.001,z+.11);o.start();o.stop(z+.12)}catch(e){}}
function burst(px,py,good){for(let i=0;i<(good?22:7);i++){let a=Math.random()*6.28,v=(good?2:1)+Math.random()*4;parts.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v-1,life:1,size:good?2+Math.random()*3:1+Math.random()*2})}}
function finish(win,reason){running=false;if(win){let bonus=Math.round(bullets*30+combo*25+(timeLeft?timeLeft*8:0));score+=bonus;if(score>best){best=score;localStorage.digShooterBest=best}hud();setTimeout(()=>panel("SCENARIO CLEARED",mode+"  •  +"+bonus+" bonus",level<scenarios.length?"NEXT SCENARIO →":"RUN COMPLETE",()=>setup(level<scenarios.length?level+1:1)),500)}
else setTimeout(()=>panel("RUN TERMINATED",reason+"<br><small>Precision beats panic.</small>","RESTART RUN",()=>setup(1)),450)}
function fire(){if(!running||paused||!bullets)return;bullets--;tracers.push({x:W/2,y:H,tx:ptr.x,ty:ptr.y,t:0});audio("shot");shake=6;
 let hit=null,dist=1e9;for(let q of targets)if(q.alive){let d=Math.hypot(ptr.x-q.x,ptr.y-q.y),r=27*q.s;if(d<r&&d<dist){hit=q;dist=d}}
 if(hit){hit.alive=false;combo++;let pts=(hit.type==="bird"?180:hit.type==="plate"?140:110)+combo*18+(hit.red?75:0);score+=pts;burst(hit.x,hit.y,true);audio("hit")}else{combo=0;score=Math.max(0,score-(scenarios[Math.min(level-1,scenarios.length-1)].red?25:10));burst(ptr.x,ptr.y,false);audio("miss")}
 hud();if(!targets.some(q=>q.alive))finish(true,"");else if(!bullets)finish(false,"Out of ammunition.");}
function panel(title,sub,button,action){msg.innerHTML="<h2>"+title+"</h2><p>"+sub+"</p><button>"+button+"</button>";msg.classList.remove("hidden");msg.querySelector("button").onclick=()=>{msg.classList.add("hidden");action()}}
function bg(t){let q=scenarios[Math.min(level-1,scenarios.length-1)],g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,q.dark?"#030406":"#0b1119");g.addColorStop(.62,q.dark?"#0a0d12":"#111b25");g.addColorStop(1,"#05080c");x.fillStyle=g;x.fillRect(0,0,W,H);x.strokeStyle="#ffffff08";for(let yy=H*.63;yy<H;yy+=28){x.beginPath();x.moveTo(0,yy);x.lineTo(W,yy);x.stroke()}x.fillStyle="#141b22";x.fillRect(0,H*.61,W,8); if(scenarios[Math.min(level-1,scenarios.length-1)].thrower){x.fillStyle="#20262c";x.fillRect(42,H*.49,6,H*.18);x.fillStyle="#2b3238";x.beginPath();x.arc(45,H*.45,15,0,6.28);x.fill();x.strokeStyle="#4b5359";x.lineWidth=7;x.beginPath();x.moveTo(47,H*.49);x.lineTo(67,H*.57);x.stroke();x.fillStyle="#79838a";x.font="700 9px system-ui";x.textAlign="left";x.fillText("THROWER",18,H*.68)}}
function target(q,t){x.save();x.translate(q.x,q.y);x.scale(q.s,q.s);
 if(q.type==="bird"){x.fillStyle="#151a20";x.beginPath();x.ellipse(0,3,9,6,0,0,6.28);x.fill();x.fillStyle="#303942";x.beginPath();x.ellipse(-12,-2,14,5,-.35,0,6.28);x.ellipse(12,-2,14,5,.35,0,6.28);x.fill();x.fillStyle="#d6a84a";x.beginPath();x.moveTo(0,3);x.lineTo(18,7);x.lineTo(1,9);x.fill();x.fillStyle="#d9dce0";x.beginPath();x.arc(-4,1,2,0,6.28);x.fill();x.restore();return}
 if(q.type==="plate"){x.fillStyle="#0008";x.beginPath();x.ellipse(0,7,25,7,0,0,6.28);x.fill();x.fillStyle=q.red?"#b94343":"#e5e7e3";x.beginPath();x.arc(0,0,22,0,6.28);x.fill();x.fillStyle="#4b5359";x.beginPath();x.arc(0,0,12,0,6.28);x.fill();x.fillStyle="#b8bec2";x.beginPath();x.arc(0,0,6,0,6.28);x.fill();x.strokeStyle="#fff7";x.lineWidth=2;x.stroke();x.restore();return}x.fillStyle="#0008";x.beginPath();x.ellipse(0,27,24,6,0,0,6.28);x.fill();if(q.red){x.strokeStyle="#d94b4b";x.lineWidth=3;x.beginPath();x.arc(0,0,23,0,6.28);x.stroke()}let g=x.createLinearGradient(-18,0,18,0);g.addColorStop(0,"#4c5155");g.addColorStop(.28,"#aeb2b1");g.addColorStop(.52,"#e1e2dd");g.addColorStop(.8,"#767b7d");g.addColorStop(1,"#34393d");x.fillStyle=g;x.beginPath();x.roundRect(-19,-3,38,31,5);x.fill();x.fillStyle="#24292e";x.fillRect(-11,-19,22,16);x.fillStyle="#9da5aa";x.fillRect(-13,-23,26,5);x.fillStyle="#fff8";x.fillRect(-13,1,4,22);x.restore()}
function pistol(){let ang=Math.atan2(ptr.y-(H+30),ptr.x-W/2);x.save();x.translate(W/2,H+38);x.rotate(ang+Math.PI/2);x.translate(0,shake);x.fillStyle="#090c10";x.beginPath();x.roundRect(-14,-74,28,76,5);x.fill();x.fillStyle="#2b3239";x.fillRect(-9,-84,18,31);x.fillStyle="#11151a";x.beginPath();x.roundRect(-13,0,26,55,4);x.fill();x.restore()}
function draw(t){x.clearRect(0,0,W,H);bg(t);drawThrower();for(let q of targets)if(q.alive)target(q,t);for(let q of tracers){let e=Math.min(1,q.t),px=q.x+(q.tx-q.x)*e,py=q.y+(q.ty-q.y)*e;x.strokeStyle="#f4d27b";x.lineWidth=2;x.beginPath();x.moveTo(q.x,q.y);x.lineTo(px,py);x.stroke()}for(let p of parts){x.globalAlpha=Math.max(0,p.life);x.fillStyle="#d6a84a";x.beginPath();x.arc(p.x,p.y,p.size,0,6.28);x.fill()}x.globalAlpha=1;pistol();if(running&&timeLeft){x.fillStyle="#fff";x.font="800 13px system-ui";x.textAlign="right";x.fillText(Math.ceil(timeLeft)+"s",W-18,25);x.fillStyle="#ffffff22";x.fillRect(18,18,W-36,3);x.fillStyle=timeLeft<10?"#e34b4b":"#d6a84a";x.fillRect(18,18,(W-36)*Math.max(0,timeLeft/scenarios[Math.min(level-1,scenarios.length-1)].time),3)}}
function tick(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;if(!paused){let q=scenarios[Math.min(level-1,scenarios.length-1)];if(running&&q.time){timeLeft-=dt;if(timeLeft<=0)finish(false,"Time expired.");}for(let q of targets)if(q.alive&&q.v){
 if(q.type==="bird"){q.x=q.bx+Math.sin(t*.001*q.v+q.ph)*W*.32*q.dir;q.y=q.by+Math.sin(t*.002*q.v+q.phase)*38}
 else if(q.type==="plate"){q.x=q.bx+Math.sin(t*.001*q.v+q.ph)*W*.28*q.dir;q.y=q.by+Math.cos(t*.0014*q.v+q.phase)*55}
 else {q.x=q.bx+Math.sin(t*.001*q.v+q.ph)*22*q.v;q.y=q.by+Math.sin(t*.001*q.v*.7+q.phase)*9}
}for(let p of parts){p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vy+=.08;p.life-=dt*1.8}parts=parts.filter(p=>p.life>0);for(let q of tracers)q.t+=dt*8;tracers=tracers.filter(q=>q.t<1);shake=Math.max(0,shake-dt*25)}draw(t);requestAnimationFrame(tick)}
function move(e){let r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;ptr.x=Math.max(0,Math.min(W,p.clientX-r.left));ptr.y=Math.max(0,Math.min(H,p.clientY-r.top));cross.style.left=ptr.x+"px";cross.style.top=ptr.y+"px"}
c.addEventListener("pointermove",move);c.addEventListener("pointerdown",e=>{move(e);fire()});c.addEventListener("touchstart",e=>{e.preventDefault();move(e);fire()},{passive:false});
$("pauseBtn").onclick=()=>{if(!running)return;paused=!paused;$("pauseBtn").textContent=paused?"▶":"Ⅱ";hint.textContent=paused?"PAUSED":"AIM • "+(timeLeft?"TIMER ACTIVE":"PRECISION OVER SPEED")};
$("soundBtn").onclick=()=>{sound=!sound;$("soundBtn").textContent=sound?"🔊":"🔇"};$("restartBtn").onclick=()=>{msg.classList.add("hidden");setup(1)};setup(1);requestAnimationFrame(tick);
})();