(()=>{"use strict";
const c=document.getElementById("gameCanvas"),ctx=c.getContext("2d"),$=id=>document.getElementById(id);
const levelEl=$("level"),targetEl=$("bottles"),ammoEl=$("bullets"),scoreEl=$("score"),bestEl=$("best"),msg=$("message"),count=$("countdown"),cross=$("crosshair"),hint=$("hint");
let W=0,H=0,dpr=1,round=1,score=0,best=Number(localStorage.getItem("digShooterBest")||0),ammo=0,targets=[],particles=[],shots=[],running=false,paused=false,sound=true,mouse={x:0,y:0},last=0,timeLeft=0,combo=0,roundConfig;
const rounds=[
 {name:"LIVE THROW",targets:9,ammo:15,speed:1.00,time:0,size:1.00,types:["bottle","bird","plate"]},
 {name:"RAPID THROW",targets:11,ammo:17,speed:1.18,time:0,size:.96,types:["bottle","bird","plate"]},
 {name:"CROSSING SKY",targets:13,ammo:19,speed:1.38,time:48,size:.92,types:["bird","plate","bottle"]},
 {name:"CLAY & GLASS",targets:15,ammo:21,speed:1.58,time:44,size:.88,types:["bottle","plate","bird"]},
 {name:"FULL RANGE",targets:18,ammo:23,speed:1.82,time:40,size:.84,types:["bottle","bird","plate"]},
 {name:"REACTION",targets:21,ammo:25,speed:2.08,time:36,size:.78,types:["bird","plate","bottle"]},
 {name:"FINAL RANGE",targets:25,ammo:28,speed:2.35,time:33,size:.72,types:["bottle","bird","plate"]}
];
function resize(){const r=c.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;c.width=W*dpr;c.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(!mouse.x){mouse.x=W/2;mouse.y=H*.45}positionCrosshair()}
addEventListener("resize",resize);
function pad(n){return String(Math.max(0,Math.floor(n))).padStart(6,"0")}
function hud(){levelEl.textContent=round;targetEl.textContent=targets.filter(t=>t.alive).length+"/"+targets.length;ammoEl.textContent=ammo;scoreEl.textContent=pad(score);bestEl.textContent=pad(best)}
function makeTargets(){targets=[];const q=roundConfig;for(let i=0;i<q.targets;i++){const type=q.types[i%q.types.length],side=i%2===0?1:-1;targets.push({type,alive:true,delay:i*.16,phase:i*.77,side,size:q.size*(type==="bird"?.88:type==="plate"?.92:1),speed:q.speed*(.9+Math.random()*.2),spin:Math.random()*6.28,age:0})}}
function startRound(n){round=n;roundConfig=rounds[Math.min(n-1,rounds.length-1)];ammo=roundConfig.ammo;timeLeft=roundConfig.time;combo=0;makeTargets();running=false;paused=false;hud();hint.textContent="THROWER ACTIVE • SHOOT BOTTLES • BIRDS • CLAY PLATES";let v=3;count.classList.remove("hidden");count.textContent=v;const timer=setInterval(()=>{v--;if(v>0)count.textContent=v;else{clearInterval(timer);count.textContent="GO";setTimeout(()=>{count.classList.add("hidden");running=true},450)}},650)}
function playSound(kind){if(!sound)return;try{window.audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.connect(g);g.connect(audioCtx.destination);o.type=kind==="shot"?"square":"sine";o.frequency.setValueAtTime(kind==="shot"?120:kind==="hit"?720:160,t);o.frequency.exponentialRampToValueAtTime(kind==="shot"?55:kind==="hit"?260:80,t+.12);g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.12);o.start();o.stop(t+.13)}catch(e){}}
function burst(x,y,hit){for(let i=0;i<(hit?24:8);i++){const a=Math.random()*Math.PI*2,v=(hit?2.2:1)+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-1,life:1,size:hit?2+Math.random()*3:1+Math.random()*2})}}
function finish(win,reason){running=false;if(win){const bonus=Math.round(ammo*18+combo*30+(timeLeft?timeLeft*7:0));score+=bonus;if(score>best){best=score;localStorage.setItem("digShooterBest",best)}hud();setTimeout(()=>showPanel("ROUND "+round+" CLEARED",round<rounds.length?roundConfig.name+" • BONUS +"+bonus:"MASTER RANGE COMPLETE • BONUS +"+bonus,round<rounds.length?"NEXT ROUND →":"PLAY AGAIN",()=>startRound(round<rounds.length?round+1:1)),400)}else{setTimeout(()=>showPanel("ROUND FAILED",reason+"<br>Targets remaining: "+targets.filter(t=>t.alive).length,"RETRY ROUND",()=>startRound(round)),400)}}
function showPanel(title,text,button,action){msg.innerHTML="<h2>"+title+"</h2><p>"+text+"</p><button>"+button+"</button>";msg.classList.remove("hidden");msg.querySelector("button").onclick=()=>{msg.classList.add("hidden");action()}}
function getTargetPosition(t,now){const p=Math.max(0,now-t.delay)*.001*t.speed*.85+t.phase;const travel=(Math.sin(p)+1)/2;let x,y;
 if(t.type==="bottle"){x=W*.14+t.side*W*.56*travel;y=H*.52-H*.34*Math.sin(travel*Math.PI);y+=Math.sin(p*2.1)*8}
 else if(t.type==="plate"){x=W*.18+t.side*W*.64*travel;y=H*.49-H*.30*Math.sin(travel*Math.PI)+Math.cos(p*1.7)*16}
 else{x=W*.10+t.side*W*.78*travel;y=H*.28+Math.sin(p*1.35)*H*.18}
 return{x,y}}
function shoot(){if(!running||paused||ammo<=0)return;ammo--;shots.push({x:W/2,y:H-48,tx:mouse.x,ty:mouse.y,life:0});playSound("shot");
 let hit=null,nearest=Infinity;for(const t of targets){if(!t.alive||t.age<.12)continue;const p=getTargetPosition(t,performance.now()),r=(t.type==="bird"?22:t.type==="plate"?25:24)*t.size,d=Math.hypot(mouse.x-p.x,mouse.y-p.y);if(d<r&&d<nearest){nearest=d;hit=t}}
 if(hit){hit.alive=false;combo++;const points=(hit.type==="bird"?180:hit.type==="plate"?150:120)+combo*20;score+=points;burst(mouse.x,mouse.y,true);playSound("hit")}else{combo=0;score=Math.max(0,score-12);burst(mouse.x,mouse.y,false);playSound("miss")}hud();if(!targets.some(t=>t.alive))finish(true,"");else if(ammo===0)finish(false,"Out of bullets.")}
function update(now,dt){if(!running||paused)return;for(const t of targets){if(t.alive)t.age+=dt*1000}if(timeLeft){timeLeft-=dt;if(timeLeft<=0){timeLeft=0;finish(false,"Time expired.")}}for(const p of particles){p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vy+=.08;p.life-=dt*1.8}particles=particles.filter(p=>p.life>0);for(const s of shots)s.life+=dt*8;shots=shots.filter(s=>s.life<1)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#0c1722");g.addColorStop(.62,"#101923");g.addColorStop(1,"#05080c");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#151e26";ctx.fillRect(0,H*.61,W,H*.39);ctx.strokeStyle="#ffffff0b";for(let y=H*.64;y<H;y+=26){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle="#2a333b";ctx.fillRect(0,H*.60,W,7)}
function drawThrower(now){const y=H*.59;ctx.save();ctx.translate(58,y);ctx.fillStyle="#10151a";ctx.beginPath();ctx.arc(0,-57,16,0,Math.PI*2);ctx.fill();ctx.fillStyle="#252d34";ctx.fillRect(-15,-40,30,58);ctx.beginPath();ctx.moveTo(-10,18);ctx.lineTo(-31,66);ctx.lineTo(-13,66);ctx.lineTo(0,32);ctx.lineTo(13,66);ctx.lineTo(31,66);ctx.lineTo(10,18);ctx.fill();ctx.strokeStyle="#aab2b7";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(7,-20);ctx.lineTo(32,-8);ctx.lineTo(45,-25);ctx.stroke();ctx.fillStyle="#8f9aa2";ctx.font="700 9px system-ui";ctx.textAlign="center";ctx.fillText("THROWER",0,82);ctx.restore()}
function drawTarget(t,now){if(!t.alive||t.age<0)return;const p=getTargetPosition(t,now),s=t.size;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(t.spin+t.age*.004*t.speed);ctx.scale(s,s);
 if(t.type==="bottle"){ctx.fillStyle="#0009";ctx.beginPath();ctx.ellipse(0,27,22,6,0,0,Math.PI*2);ctx.fill();let g=ctx.createLinearGradient(-17,0,17,0);g.addColorStop(0,"#4e5559");g.addColorStop(.35,"#e7e8e2");g.addColorStop(.6,"#a2a8aa");g.addColorStop(1,"#343a3d");ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(-18,-3,36,30,5);ctx.fill();ctx.fillStyle="#252b30";ctx.fillRect(-10,-19,20,16);ctx.fillStyle="#aeb5b8";ctx.fillRect(-13,-24,26,5);ctx.fillStyle="#fff8";ctx.fillRect(-12,1,4,21)}
 else if(t.type==="plate"){ctx.fillStyle="#e1e3df";ctx.beginPath();ctx.arc(0,0,23,0,Math.PI*2);ctx.fill();ctx.fillStyle="#596268";ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke()}
 else{ctx.fillStyle="#14191e";ctx.beginPath();ctx.ellipse(0,0,11,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#303a42";ctx.beginPath();ctx.ellipse(-14,-3,16,5,-.45,0,Math.PI*2);ctx.ellipse(14,-3,16,5,.45,0,Math.PI*2);ctx.fill();ctx.fillStyle="#d6a84a";ctx.beginPath();ctx.moveTo(9,1);ctx.lineTo(25,5);ctx.lineTo(9,7);ctx.fill();ctx.fillStyle="#eee";ctx.beginPath();ctx.arc(5,-2,2,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawGun(){const gx=W/2,gy=H-20,ang=Math.atan2(mouse.y-(H-72),mouse.x-gx);ctx.save();ctx.translate(gx,gy);ctx.rotate(ang+Math.PI/2);ctx.fillStyle="#080b0e";ctx.beginPath();ctx.roundRect(-13,-65,26,62,5);ctx.fill();ctx.fillStyle="#303940";ctx.fillRect(-8,-76,16,25);ctx.fillStyle="#11161b";ctx.beginPath();ctx.roundRect(-12,-3,24,47,4);ctx.fill();ctx.restore()}
function render(now){ctx.clearRect(0,0,W,H);drawBackground();drawThrower(now);for(const t of targets)drawTarget(t,now);for(const s of shots){const e=Math.min(1,s.life),px=s.x+(s.tx-s.x)*e,py=s.y+(s.ty-s.y)*e;ctx.strokeStyle="#f4d27b";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(px,py);ctx.stroke()}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle="#d6a84a";ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;drawGun();if(running&&timeLeft){ctx.fillStyle="#fff";ctx.font="800 13px system-ui";ctx.textAlign="right";ctx.fillText(Math.ceil(timeLeft)+"s",W-18,26);ctx.fillStyle="#d6a84a";ctx.fillRect(18,18,(W-36)*Math.max(0,timeLeft/roundConfig.time),3)}}
function loop(now){const dt=Math.min(.035,(now-last)/1000||0);last=now;update(now,dt);render(now);requestAnimationFrame(loop)}
function move(e){const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;mouse.x=Math.max(0,Math.min(W,p.clientX-r.left));mouse.y=Math.max(0,Math.min(H,p.clientY-r.top));positionCrosshair()}
function positionCrosshair(){cross.style.left=mouse.x+"px";cross.style.top=mouse.y+"px"}
c.addEventListener("pointermove",move);c.addEventListener("pointerdown",e=>{move(e);shoot()});c.addEventListener("touchstart",e=>{e.preventDefault();move(e);shoot()},{passive:false});
$("pauseBtn").onclick=()=>{if(!running)return;paused=!paused;$("pauseBtn").textContent=paused?"▶":"Ⅱ";hint.textContent=paused?"PAUSED":"THROWER ACTIVE • TRACK THE AIRBORNE TARGETS"};
$("soundBtn").onclick=()=>{sound=!sound;$("soundBtn").textContent=sound?"🔊":"🔇"};
$("restartBtn").onclick=()=>{msg.classList.add("hidden");startRound(1)};
resize();startRound(1);requestAnimationFrame(loop);
})();